services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: ./cmd/api
    environment:
      - APP_PORT=${APP_PORT}
      - ENV=${ENV}
    depends_on:
      - postgres
